create table sys_oper_log
(
    oper_id        bigint auto_increment comment '日志主键'
        primary key,
    title          varchar(50)   default '' null comment '模块标题',
    business_type  int           default 0  null comment '业务类型（0其它 1新增 2修改 3删除）',
    method         varchar(100)  default '' null comment '方法名称',
    request_method varchar(10)   default '' null comment '请求方式',
    operator_type  int           default 0  null comment '操作类别（0其它 1后台用户 2手机端用户）',
    oper_name      varchar(50)   default '' null comment '操作人员',
    dept_name      varchar(50)   default '' null comment '部门名称',
    oper_url       varchar(255)  default '' null comment '请求URL',
    oper_ip        varchar(128)  default '' null comment '主机地址',
    oper_location  varchar(255)  default '' null comment '操作地点',
    oper_param     varchar(2000) default '' null comment '请求参数',
    json_result    varchar(2000) default '' null comment '返回参数',
    status         int           default 0  null comment '操作状态（0正常 1异常）',
    error_msg      varchar(2000) default '' null comment '错误消息',
    oper_time      datetime                 null comment '操作时间',
    cost_time      bigint        default 0  null comment '消耗时间'
)
    comment '操作日志记录';

create index idx_sys_oper_log_bt
    on sys_oper_log (business_type);

create index idx_sys_oper_log_ot
    on sys_oper_log (oper_time);

create index idx_sys_oper_log_s
    on sys_oper_log (status);

INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (1, '操作日志', 9, 'com.ruoyi.system.controller.SysOperlogController.clean()', 'DELETE', 1, 'admin', null, '/operlog/clean', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-05 15:48:14', 49);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (2, '菜单管理', 1, 'com.ruoyi.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createBy":"admin","icon":"list","isCache":"0","isFrame":"1","menuName":"快速连接","menuType":"M","orderNum":4,"params":{},"parentId":0,"path":"1","status":"0","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-05 15:52:02', 41);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (3, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createTime":"2024-05-05 15:52:02","icon":"list","isCache":"0","isFrame":"1","menuId":2000,"menuName":"快速连接","menuType":"M","orderNum":4,"params":{},"parentId":0,"path":"/link","perms":"","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-05 15:52:46', 26);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (4, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createTime":"2024-05-05 15:52:02","icon":"list","isCache":"0","isFrame":"1","menuId":2000,"menuName":"快速连接","menuType":"M","orderNum":4,"params":{},"parentId":0,"path":"link","perms":"","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-05 15:53:34', 25);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (5, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createTime":"2024-05-05 14:20:25","icon":"guide","isCache":"0","isFrame":"0","menuId":4,"menuName":"若依官网","menuType":"M","orderNum":4,"params":{},"parentId":2000,"path":"http://ruoyi.vip","perms":"","query":"","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-05 15:54:40', 22);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (6, '菜单管理', 1, 'com.ruoyi.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createBy":"admin","icon":"eye-open","isCache":"0","isFrame":"1","menuName":"爬虫模块","menuType":"M","orderNum":5,"params":{},"parentId":0,"path":"crawler","status":"0","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-06 11:51:14', 30);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (7, '菜单管理', 1, 'com.ruoyi.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createBy":"admin","icon":"client","isCache":"0","isFrame":"1","menuName":"哔哩哔哩","menuType":"C","orderNum":1,"params":{},"parentId":2001,"path":"/bili","perms":"crawler:bili","status":"0","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-06 11:53:09', 27);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (8, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"createTime":"2024-05-06 11:53:09","icon":"client","isCache":"0","isFrame":"1","menuId":2002,"menuName":"哔哩哔哩","menuType":"C","orderNum":1,"params":{},"parentId":2001,"path":"bili","perms":"crawler:bili","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-06 11:54:18', 37);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (9, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"component":"crawler/bili/index","createTime":"2024-05-06 11:53:09","icon":"client","isCache":"0","isFrame":"1","menuId":2002,"menuName":"哔哩哔哩","menuType":"C","orderNum":1,"params":{},"parentId":2001,"path":"bili","perms":"crawler:bili","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-06 11:57:06', 22);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (10, '代码生成', 6, 'com.ruoyi.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', '{"tables":"crawler_bili_info"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-06 15:25:51', 122);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (11, '代码生成', 8, 'com.ruoyi.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', '{"tables":"crawler_bili_info"}', null, 0, null, '2024-05-06 15:25:55', 136);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (12, '参数管理', 9, 'com.ruoyi.system.controller.SysConfigController.refreshCache()', 'DELETE', 1, 'admin', null, '/config/refreshCache', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 01:29:36', 35);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (13, '参数管理', 2, 'com.ruoyi.system.controller.SysConfigController.edit()', 'PUT', 1, 'admin', null, '/config', '127.0.0.1', '', '{"configId":4,"configKey":"sys.account.registerUser","configName":"账号自助-是否开启用户注册功能","configType":"Y","configValue":"true","createBy":"admin","createTime":"2024-05-05 14:20:29","params":{},"remark":"是否开启注册用户功能（true开启，false关闭）","updateBy":"admin"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 01:29:47', 13);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (14, '角色管理', 2, 'com.ruoyi.system.controller.SysRoleController.edit()', 'PUT', 1, 'admin', null, '/role', '127.0.0.1', '', '{"admin":false,"createTime":"2024-05-05 15:16:22","dataScope":"1","delFlag":"0","deptCheckStrictly":true,"flag":false,"menuCheckStrictly":true,"menuIds":[2000,4,2001,2002],"params":{},"remark":"普通用户","roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0","updateBy":"admin"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 01:32:38', 41);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (15, '用户管理', 2, 'com.ruoyi.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"admin":false,"avatar":"","createBy":"admin","createTime":"2024-05-05 15:18:30","delFlag":"0","dept":{"ancestors":"0","children":[],"deptId":100,"deptName":"晚风科技","leader":"刘卓昊","orderNum":0,"params":{},"parentId":0,"status":"0"},"deptId":100,"email":"804121985@qq.com","loginIp":"","nickName":"晚风","params":{},"phonenumber":"13453665895","postIds":[5],"remark":"测试用","roleIds":[100],"roles":[{"admin":false,"dataScope":"1","deptCheckStrictly":false,"flag":false,"menuCheckStrictly":false,"params":{},"roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0"}],"sex":"0","status":"0","updateBy":"admin","userId":100,"userName":"wanfeng"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 01:33:16', 30);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (16, '在线用户', 7, 'com.ruoyi.system.controller.SysUserOnlineController.forceLogout()', 'DELETE', 1, 'admin', null, '/online/71b62717-f253-4b71-a8dc-019590a5badf', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 01:34:38', 5);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (17, '代码生成', 3, 'com.ruoyi.gen.controller.GenController.remove()', 'DELETE', 1, 'admin', null, '/gen/1', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 09:32:37', 89);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (18, '代码生成', 6, 'com.ruoyi.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', '{"tables":"sys_user_push_prop"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 09:32:42', 81);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (19, '用户管理', 2, 'com.ruoyi.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"admin":false,"avatar":"","createBy":"admin","createTime":"2024-05-05 15:18:30","delFlag":"0","dept":{"ancestors":"0","children":[],"deptId":100,"deptName":"晚风科技","leader":"刘卓昊","orderNum":0,"params":{},"parentId":0,"status":"0"},"deptId":100,"email":"804121985@qq.com","loginIp":"","nickName":"晚风","params":{},"phonenumber":"13453665895","postIds":[5],"remark":"测试用","roleIds":[100],"roles":[{"admin":false,"dataScope":"1","deptCheckStrictly":false,"flag":false,"menuCheckStrictly":false,"params":{},"roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0"}],"sex":"0","status":"0","updateBy":"admin","userId":100,"userName":"wanfeng"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 09:59:16', 49);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (20, '用户管理', 2, 'com.ruoyi.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"admin":false,"avatar":"","createBy":"admin","createTime":"2024-05-05 15:18:30","delFlag":"0","dept":{"ancestors":"0","children":[],"deptId":100,"deptName":"晚风科技","leader":"刘卓昊","orderNum":0,"params":{},"parentId":0,"status":"0"},"deptId":100,"email":"804121985@qq.com","loginIp":"","nickName":"晚风","params":{},"phonenumber":"13453665895","postIds":[5],"remark":"测试用","roleIds":[100],"roles":[{"admin":false,"dataScope":"1","deptCheckStrictly":false,"flag":false,"menuCheckStrictly":false,"params":{},"roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0"}],"sex":"0","status":"0","updateBy":"admin","userId":100,"userName":"wanfeng"}', null, 1, 'Cannot cast java.lang.Object to java.lang.String', '2024-05-07 11:00:26', 54);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (21, '用户管理', 2, 'com.ruoyi.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"admin":false,"avatar":"","createBy":"admin","createTime":"2024-05-05 15:18:30","delFlag":"0","dept":{"ancestors":"0","children":[],"deptId":100,"deptName":"晚风科技","leader":"刘卓昊","orderNum":0,"params":{},"parentId":0,"status":"0"},"deptId":100,"email":"804121985@qq.com","loginIp":"","nickName":"晚风","params":{},"phonenumber":"13453665895","postIds":[5],"remark":"测试用","roleIds":[100],"roles":[{"admin":false,"dataScope":"1","deptCheckStrictly":false,"flag":false,"menuCheckStrictly":false,"params":{},"roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0"}],"sex":"0","status":"0","updateBy":"admin","userId":100,"userName":"wanfeng"}', null, 1, '
### Error updating database.  Cause: java.sql.SQLException: Field \'base_url\' doesn\'t have a default value
### The error may exist in com/ruoyi/system/mapper/PushPropertiesMapper.java (best guess)
### The error may involve com.ruoyi.system.mapper.PushPropertiesMapper.insert-Inline
### The error occurred while setting parameters
### SQL: INSERT INTO sys_user_push_prop  ( user_id,  icon )  VALUES  ( ?,  ? )
### Cause: java.sql.SQLException: Field \'base_url\' doesn\'t have a default value
; Field \'base_url\' doesn\'t have a default value; nested exception is java.sql.SQLException: Field \'base_url\' doesn\'t have a default value', '2024-05-07 11:01:09', 121);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (22, '用户管理', 2, 'com.ruoyi.system.controller.SysUserController.edit()', 'PUT', 1, 'admin', null, '/user', '127.0.0.1', '', '{"admin":false,"avatar":"","createBy":"admin","createTime":"2024-05-05 15:18:30","delFlag":"0","dept":{"ancestors":"0","children":[],"deptId":100,"deptName":"晚风科技","leader":"刘卓昊","orderNum":0,"params":{},"parentId":0,"status":"0"},"deptId":100,"email":"804121985@qq.com","loginIp":"","nickName":"晚风","params":{},"phonenumber":"13453665895","postIds":[5],"remark":"测试用","roleIds":[100],"roles":[{"admin":false,"dataScope":"1","deptCheckStrictly":false,"flag":false,"menuCheckStrictly":false,"params":{},"roleId":100,"roleKey":"user","roleName":"普通用户","roleSort":2,"status":"0"}],"sex":"0","status":"0","updateBy":"admin","userId":100,"userName":"wanfeng"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-07 16:04:57', 74);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (23, '代码生成', 3, 'com.ruoyi.gen.controller.GenController.remove()', 'DELETE', 1, 'admin', null, '/gen/2', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:24:05', 71);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (24, '代码生成', 6, 'com.ruoyi.gen.controller.GenController.importTableSave()', 'POST', 1, 'admin', null, '/gen/importTable', '127.0.0.1', '', '{"tables":"sys_push_config"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:24:35', 66);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (25, '代码生成', 2, 'com.ruoyi.gen.controller.GenController.editSave()', 'PUT', 1, 'admin', null, '/gen', '127.0.0.1', '', '{"businessName":"pushConfig","className":"SysPushConfig","columns":[{"capJavaField":"Id","columnId":9,"columnName":"id","columnType":"int","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":false,"htmlType":"input","increment":true,"insert":true,"isIncrement":"1","isInsert":"1","isPk":"1","javaField":"id","javaType":"Long","list":false,"params":{},"pk":true,"query":false,"queryType":"EQ","required":false,"sort":1,"superColumn":false,"tableId":3,"updateBy":"","usableColumn":false},{"capJavaField":"Type","columnComment":"","columnId":10,"columnName":"type","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"select","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"type","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":2,"superColumn":false,"tableId":3,"updateBy":"","usableColumn":false},{"capJavaField":"BaseUrl","columnId":11,"columnName":"baseUrl","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"baseUrl","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":3,"superColumn":false,"tableId":3,"updateBy":"","usableColumn":false},{"capJavaField":"OtherNeed","columnId":12,"columnName":"other_need","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"otherNeed","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":4,"superColumn":false,', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:26:45', 38);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (26, '代码生成', 8, 'com.ruoyi.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', '{"tables":"sys_push_config"}', null, 0, null, '2024-05-08 22:26:47', 118);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (27, '代码生成', 8, 'com.ruoyi.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', '{"tables":"sys_push_config"}', null, 0, null, '2024-05-08 22:41:22', 127);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (28, '代码生成', 2, 'com.ruoyi.gen.controller.GenController.editSave()', 'PUT', 1, 'admin', null, '/gen', '127.0.0.1', '', '{"businessName":"pushConfig","className":"SysPushConfig","columns":[{"capJavaField":"Id","columnComment":"id","columnId":9,"columnName":"id","columnType":"int","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":false,"htmlType":"input","increment":true,"insert":true,"isIncrement":"1","isInsert":"1","isPk":"1","javaField":"id","javaType":"Long","list":false,"params":{},"pk":true,"query":false,"queryType":"EQ","required":false,"sort":1,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:26:45","usableColumn":false},{"capJavaField":"Type","columnComment":"推送类型","columnId":10,"columnName":"type","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"select","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"type","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":2,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:26:45","usableColumn":false},{"capJavaField":"BaseUrl","columnComment":"基础URL","columnId":11,"columnName":"baseUrl","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"baseUrl","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":3,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:26:45","usableColumn":false},{"capJavaField":"OtherNeed","columnComment":"其他需要的数据","columnId":12,"columnName":"other_need","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1",', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:44:16', 63);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (29, '字典类型', 1, 'com.ruoyi.system.controller.SysDictTypeController.add()', 'POST', 1, 'admin', null, '/dict/type', '127.0.0.1', '', '{"createBy":"admin","dictName":"系统推送服务","dictType":"sys_push_config","params":{},"status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:45:01', 21);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (30, '字典数据', 1, 'com.ruoyi.system.controller.SysDictDataController.add()', 'POST', 1, 'admin', null, '/dict/data', '127.0.0.1', '', '{"createBy":"admin","default":false,"dictLabel":"Bark","dictSort":1,"dictType":"sys_push_config","dictValue":"bark","listClass":"default","params":{},"remark":"IOS系统的bark APP","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:46:16', 37);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (31, '字典类型', 9, 'com.ruoyi.system.controller.SysDictTypeController.refreshCache()', 'DELETE', 1, 'admin', null, '/dict/type/refreshCache', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:46:21', 73);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (32, '代码生成', 2, 'com.ruoyi.gen.controller.GenController.editSave()', 'PUT', 1, 'admin', null, '/gen', '127.0.0.1', '', '{"businessName":"pushConfig","className":"SysPushConfig","columns":[{"capJavaField":"Id","columnComment":"id","columnId":9,"columnName":"id","columnType":"int","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":false,"htmlType":"input","increment":true,"insert":true,"isIncrement":"1","isInsert":"1","isPk":"1","javaField":"id","javaType":"Long","list":false,"params":{},"pk":true,"query":false,"queryType":"EQ","required":false,"sort":1,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:44:16","usableColumn":false},{"capJavaField":"Type","columnComment":"推送类型","columnId":10,"columnName":"type","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"sys_push_config","edit":true,"htmlType":"select","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"type","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":2,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:44:16","usableColumn":false},{"capJavaField":"BaseUrl","columnComment":"基础URL","columnId":11,"columnName":"baseUrl","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1","isList":"1","isPk":"0","isQuery":"1","javaField":"baseUrl","javaType":"String","list":true,"params":{},"pk":false,"query":true,"queryType":"EQ","required":false,"sort":3,"superColumn":false,"tableId":3,"updateBy":"","updateTime":"2024-05-08 22:44:16","usableColumn":false},{"capJavaField":"OtherNeed","columnComment":"其他需要的数据","columnId":12,"columnName":"other_need","columnType":"varchar(255)","createBy":"admin","createTime":"2024-05-08 22:24:35","dictType":"","edit":true,"htmlType":"input","increment":false,"insert":true,"isEdit":"1","isIncrement":"0","isInsert":"1', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:47:16', 41);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (33, '代码生成', 8, 'com.ruoyi.gen.controller.GenController.batchGenCode()', 'GET', 1, 'admin', null, '/gen/batchGenCode', '127.0.0.1', '', '{"tables":"sys_push_config"}', null, 0, null, '2024-05-08 22:47:19', 45);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (34, '推送服务', 1, 'com.ruoyi.system.controller.SysPushConfigController.add()', 'POST', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"123","id":1,"otherNeed":"123","params":{}}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:52:54', 53);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (35, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"123","id":1,"otherNeed":"123","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:54:43', 42);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (36, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"https://api.day.app/","id":1,"otherNeed":"无","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:56:23', 43);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (37, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"component":"system/pushConfig/index","createTime":"2024-05-08 22:37:47","icon":"email","isCache":"0","isFrame":"1","menuId":2003,"menuName":"推送服务","menuType":"C","orderNum":1,"params":{},"parentId":1,"path":"pushConfig","perms":"system:pushConfig:list","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 22:56:54', 20);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (38, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"https://api.day.app/","id":1,"otherNeed":"用户获得的Token直接拼接到URL后","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-08 23:03:06', 20);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (39, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"https://api.day.app1/","id":1,"otherNeed":"用户获得的Token直接拼接到URL后","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-09 00:21:16', 52);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (40, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"https://api.day.app/","id":1,"otherNeed":"用户获得的Token直接拼接到URL后","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-09 00:22:37', 14);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (41, '字典数据', 2, 'com.ruoyi.system.controller.SysDictDataController.edit()', 'PUT', 1, 'admin', null, '/dict/data', '127.0.0.1', '', '{"createBy":"admin","createTime":"2024-05-08 22:46:16","default":false,"dictCode":100,"dictLabel":"IOS:Bark","dictSort":1,"dictType":"sys_push_config","dictValue":"bark","isDefault":"N","listClass":"default","params":{},"remark":"IOS系统的bark APP","status":"0","updateBy":"admin"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-09 00:25:43', 32);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (42, '菜单管理', 1, 'com.ruoyi.system.controller.SysMenuController.add()', 'POST', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"component":"crawler/push/index","createBy":"admin","icon":"email","isCache":"0","isFrame":"1","menuName":"推送管理","menuType":"C","orderNum":2,"params":{},"parentId":2002,"path":"crawler.push","status":"0","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-09 00:33:59', 31);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (43, '菜单管理', 2, 'com.ruoyi.system.controller.SysMenuController.edit()', 'PUT', 1, 'admin', null, '/menu', '127.0.0.1', '', '{"children":[],"component":"crawler/push/index","createTime":"2024-05-09 00:33:59","icon":"email","isCache":"0","isFrame":"1","menuId":2009,"menuName":"推送管理","menuType":"C","orderNum":2,"params":{},"parentId":2001,"path":"push","perms":"crawler:push","status":"0","updateBy":"admin","visible":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-09 00:34:31', 29);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (44, '字典数据', 1, 'com.ruoyi.system.controller.SysDictDataController.add()', 'POST', 1, 'admin', null, '/dict/data', '127.0.0.1', '', '{"createBy":"admin","default":false,"dictLabel":"email","dictSort":2,"dictType":"sys_push_config","dictValue":"email","listClass":"default","params":{},"status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-10 23:20:36', 15);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (45, '字典数据', 2, 'com.ruoyi.system.controller.SysDictDataController.edit()', 'PUT', 1, 'admin', null, '/dict/data', '127.0.0.1', '', '{"createBy":"admin","createTime":"2024-05-10 23:20:36","default":false,"dictCode":101,"dictLabel":"email","dictSort":2,"dictType":"sys_push_config","dictValue":"email","isDefault":"N","listClass":"default","params":{},"remark":"邮件发送","status":"0","updateBy":"admin"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-10 23:20:44', 19);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (46, '推送服务', 1, 'com.ruoyi.system.controller.SysPushConfigController.add()', 'POST', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"NULL","id":2,"otherNeed":"NULL","params":{},"type":"email"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-10 23:21:09', 20);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (47, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"https://api.day.app/","id":1,"otherNeed":"基于IOS系统的APP，可直接推送到Iphone","params":{},"type":"bark"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-10 23:30:23', 39);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (48, '推送服务', 2, 'com.ruoyi.system.controller.SysPushConfigController.edit()', 'PUT', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"NULL","id":2,"otherNeed":"基于邮箱发送数据","params":{},"type":"email"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-10 23:30:33', 14);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (49, '字典数据', 1, 'com.ruoyi.system.controller.SysDictDataController.add()', 'POST', 1, 'admin', null, '/dict/data', '127.0.0.1', '', '{"createBy":"admin","default":false,"dictLabel":"TEST","dictSort":3,"dictType":"sys_push_config","dictValue":"TEST","listClass":"default","params":{},"remark":"TEST","status":"0"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-11 00:04:19', 37);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (50, '字典类型', 9, 'com.ruoyi.system.controller.SysDictTypeController.refreshCache()', 'DELETE', 1, 'admin', null, '/dict/type/refreshCache', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-11 00:04:32', 56);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (51, '推送服务', 1, 'com.ruoyi.system.controller.SysPushConfigController.add()', 'POST', 1, 'admin', null, '/pushConfig', '127.0.0.1', '', '{"baseUrl":"TEST","id":3,"otherNeed":"TEST","params":{},"type":"TEST"}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-11 00:04:45', 26);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (52, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2003', '127.0.0.1', '', '{}', '{"msg":"存在子菜单,不允许删除","code":601}', 0, null, '2024-05-16 09:15:46', 12);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (53, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2004', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:15:51', 39);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (54, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2005', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:15:53', 21);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (55, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2006', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:15:54', 15);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (56, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2007', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:15:56', 12);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (57, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2008', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:15:58', 22);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (58, '菜单管理', 3, 'com.ruoyi.system.controller.SysMenuController.remove()', 'DELETE', 1, 'admin', null, '/menu/2003', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:16:00', 18);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (59, '字典类型', 3, 'com.ruoyi.system.controller.SysDictTypeController.remove()', 'DELETE', 1, 'admin', null, '/dict/type/100', '127.0.0.1', '', '{}', null, 1, '系统推送服务已分配,不能删除', '2024-05-16 09:16:53', 11);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (60, '字典类型', 3, 'com.ruoyi.system.controller.SysDictDataController.remove()', 'DELETE', 1, 'admin', null, '/dict/data/100', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:16:59', 33);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (61, '字典类型', 3, 'com.ruoyi.system.controller.SysDictDataController.remove()', 'DELETE', 1, 'admin', null, '/dict/data/101', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:17:00', 25);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (62, '字典类型', 3, 'com.ruoyi.system.controller.SysDictDataController.remove()', 'DELETE', 1, 'admin', null, '/dict/data/102', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:17:01', 19);
INSERT INTO `ry-cloud`.sys_oper_log (oper_id, title, business_type, method, request_method, operator_type, oper_name, dept_name, oper_url, oper_ip, oper_location, oper_param, json_result, status, error_msg, oper_time, cost_time) VALUES (63, '字典类型', 3, 'com.ruoyi.system.controller.SysDictTypeController.remove()', 'DELETE', 1, 'admin', null, '/dict/type/100', '127.0.0.1', '', '{}', '{"msg":"操作成功","code":200}', 0, null, '2024-05-16 09:17:05', 37);
